name: Go with matrix

on: [push]

jobs:
   build:
    
     strategy:
      matrix:
        go-version: [ '1.14', '1.15', '1.16.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
        
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
     -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
           push: true
           tags: shush77sarg/goapp:latest
      
